server:
  port: 8100
spring:
  cloud:
    function:
      definition: toUpperCase;toLowerCase # 支持 single application可以有多个消费者或生产者
    stream:
      bindings:
        toUpperCase-in-0:
          group: consumer-group_01
          destination: topic-test-02
        toLowerCase-in-0:
          group: consumer-group_02
          destination: topic-test-02
#          content-type: text/plain
#        sink-in-0:
#          group: consumer-group_01
#          destination: topic-test-02
#          content-type: text/plain
#        stringSupplier-out-0:
#          destination: topic-test-02
#          content-type: text/plain
      kafka:
        binder:
          brokers: 81.68.76.15:9092
          configuration:
            key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
            value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer